### ISSUE TITLE
On update nodes

### ISSUE THREAD

**Issue by rektuiemforameme** [rektuiemforameme/GreasePencil2DMorphs#1]
*This issue was originally posted in the wrong repo, so I'm making the issue here. -Matt*

Very good addon, I was looking for something like that a long time ago

```
Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops_nodes.py", line 22, in execute
    run_ops_without_view_layer_update(update_nodes,self,context,self.mode)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/utils_ops.py", line 29, in run_ops_without_view_layer_update
    func(*args)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops_nodes.py", line 358, in update_nodes
    m.generate(context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/nodes/Output/node_GPMorph.py", line 115, in generate
    generate_2d_morphs_with_pg(self.props,self.name,self.get_pass_index(),False,False,editor_props.mode)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 1537, in generate_2d_morphs_with_pg
    bpy.ops.gp2dmorphs.generate_2d_morphs(
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 81, in execute
    run_ops_without_view_layer_update(self.run,context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/utils_ops.py", line 29, in run_ops_without_view_layer_update
    func(*args)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 112, in run
    generate_morph_frames(self,context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 1675, in generate_morph_frames
    else:               self.reset_gp_layers_status(gp,multiple_layers,original_layer_locked=original_layer_locked,original_active_layer=original_active_layer,original_autolock=original_autolock)
  File "/usr/share/blender/3.6/scripts/modules/bpy_types.py", line 858, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'GP2DMORPHS_OT_generate_2d_morphs' object has no attribute 'reset_gp_layers_status'
Ubicación: /usr/share/blender/3.6/scripts/modules/bpy/ops.py:113
```

**Comment by rektuiemforameme** [comment]
Ok, I know what the issue is, and it's kinda dumb. I'm going to push changes that will fix that and some other things soon, but you can ignore this error for now because it should only happen if the frame generation fails anyway. It fails because you don't have all corners of your defined frames defined. The addon would usually show an error message telling you this, but it crashes before it can do so because I changed some things and then didn't fix every part of the code that references that change. If you define all of the corners, you shouldn't have this issue. Let me know if this isn't the case.

**Comment by b4zz4** [comment]
In my animation, I didn't need to regenerate the frames, so it generated a mistake. Solve the problem by deactivating frames item.

![2023-11-26-192755_239x87_scrot](https://github.com/rektuiemforameme/GreasePencil2DMorphs/assets/643833/4f307ad9-59e5-4dcd-befb-b66c1fa91a1d)

**Comment by rektuiemforameme** [comment]
You can also stop frames from being regenerated by toggling the "lock frames" option in the morph node's properties.
![Lock Morph](https://i.imgur.com/D4mAJa5.png)
In this image it's "Lock Morph" because in the patch I'm working on I renamed it and gave the option to bone morphs as well.
